obj-$(CONFIG_MSM_CAMERA) += mt9t013.o#mt9p012.o mt9t013.o mt9d112.o #//FIH_ADQ,JOE HSU
obj-$(CONFIG_ARCH_MSM) += msm_vfe7x.o msm_io7x.o
#obj-$(CONFIG_ARCH_QSD) += msm_vfe8x.o msm_vfe8x_proc.o msm_io8x.o #//FIH_ADQ,JOE HSU
