CC := $(ATH_CROSS_COMPILE_TYPE)gcc

all:
	$(CC) -Wall -I../../include -I../../../include -I../../os/linux/include rompatcher.c -o rompatcher
	$(CC) -Wall -I../../include -I../../../include -I../../os/linux/include fwpatch.c -o fwpatch
